import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import MuiThemeProvider from './_components/MuiThemeProvider';
import clashDisplayFont, { satoshiFont } from './fonts/clash-display';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${clashDisplayFont.variable} ${satoshiFont.variable}`}>
      <body
        style={{
          fontFamily: 'var(--font-clash-display), sans-serif',
        }}
      >
        <AppRouterCacheProvider options={{ key: 'css', enableCssLayer: true }}>
          <MuiThemeProvider>{children}</MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
